### ISSUE TITLE
TypeError: Data location must be "storage" or "memory" for constructor parameter, but "calldata" was given.

### ISSUE THREAD

**Issue by rhcproc** [chiru-labs/PBT#15]
The simple mint example provided in README.md causes the following error in Remix.
TypeError: Data location must be "storage" or "memory" for the constructor parameter, but "calldata" was given.
The parameters of the constructor provided in the example should be changed as follows.
- constructor(address[] memory chipAddresses, uint256[] memory tokenIds)

**Comment by 2pmflow** [comment]
Thanks

**Comment by cygaar** [comment]
Thanks for bringing this up. Fixed this and a couple other issues with the readme

**Comment by rhcproc** [comment]
Thanks for applying this issue.
